### ISSUE TITLE
Available seats

### ISSUE THREAD

**Issue by jagedn** [scaballe/MIJE-PDS2#3]
Seria mas legible que available sheets de un trip se mantuviera al valor inicial indicado por el driver y no modificarlo cuando se añade un passenger

**Comment by emiliew** [comment]
Vale, y controlar con que el getPassengers sea siempre menor que
availableSeats.
No problemo!

On Tue, 1 Dec 2015 20:47 Jorge <notifications@github.com> wrote:

> Seria mas legible que available sheets de un trip se mantuviera al valor
> inicial indicado por el driver y no modificarlo cuando se añade un passenger
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scaballe/MIJE-PDS2/issues/3>.
>
-- 

Emilio Molina

**Comment by emiliew** [comment]
Menor o igual, claro.

On Tue, 1 Dec 2015 21:08 Emilio Molina <emiliomolinaharo@gmail.com> wrote:

> Vale, y controlar con que el getPassengers sea siempre menor que
> availableSeats.
> No problemo!
>
> On Tue, 1 Dec 2015 20:47 Jorge <notifications@github.com> wrote:
>
>> Seria mas legible que available sheets de un trip se mantuviera al valor
>> inicial indicado por el driver y no modificarlo cuando se añade un passenger
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/scaballe/MIJE-PDS2/issues/3>.
>>
> --
>
> Emilio Molina
>
-- 

Emilio Molina
