### ISSUE TITLE
Como llamar a un managed bean con context.lookup

### ISSUE THREAD

**Issue by ipintor** [scaballe/MIJE-PDS2#5]
He probado de varias maneras, pero no lo consigo. Quiero que al hacer login aparezca en la portada una tabla (bastante cutre) con la lista de coches del usuario, pero cuando llamo al bean se jode y me dice que no encuentra el nombre. Estoy poniendo esto:

carsRemote = (UserFacadeRemote) ctx.lookup("java:app/CarSharingMije.jar/UserFacadeBean!ejb.UserFacadeRemote");

¿Alguien sabe la manera correcta de identificar al bean? ¿Jorge tal vez?

**Comment by jagedn** [comment]
primero asegurate que al ejb lo estas etiquetando como Stateless

lo segundo, es mucho mas facil y comodo usar las etiquetas y la inyeccion para tener una referencia al ejb desde el bean.

si ves los otros jsf veras que hacen

@EJB
	private TripAdminFacadeRemote AddTripRemote;
	

y te olvidas del lookup y todo eso

**Comment by ipintor** [comment]
Ok, cierro esto porque creo que ya lo tengo.
