### ISSUE TITLE
ayuda con EJB

### ISSUE THREAD

**Issue by ipintor** [scaballe/MIJE-PDS2#6]
[errorLog.txt](https://github.com/scaballe/MIJE-PDS2/files/55454/errorLog.txt)

Después de darle muuchas vueltas a la lista de coches, consigo que el managed bean listCars encuentre al EJB, este hace la llamada a la BD, y consigue los resultados (por ahora solo busca y encuentra un opel corsa que he añadido a mano). Y cuando ya lo tiene (que lo tiene, porque lo he visto en modo depuracion) y lo va a mandar de vuelta al managed bean para que lo pueda mostrar el facelet, sale el error que adjunto.

¿Alguien tiene idea de donde estoy metiendo la pata?

**Comment by jagedn** [comment]
Hola

segun este enlace hay que poner un fichero con un contenido especifico:
http://stackoverflow.com/questions/10692495/classnotfoundexception-marshaling-ejb-parameters-on-jboss7

Ya lo he creado y lo subo en el proximo commit

**Comment by jagedn** [comment]
Parece ser que los tipos básicos no están soportados en los beans del modelo. He cambiado los int a Integer y lo subo en el proximo commit (probado y funciona)
