### ISSUE TITLE
Fecha de Trip en la carga del modelo

### ISSUE THREAD

**Issue by emiliew** [scaballe/MIJE-PDS2#8]
En la carga del modelo, al insertar Trips, la instrucción "Calendar.getInstance().getTime()" toma la hora, minuto y segundo del momento. 
En el momento de búsqueda Trips, sólo se introduce la fecha, estos campos no se introducen, por lo que están a 0. Al buscar en tabla no encuentra nada para ese día por la discordancia de hora.
En la carga de datos habrá de meterse únicamente el Date, dejando el Time a 0.

**Comment by jagedn** [comment]
habria que separar los campos date en dos (date y time) como explican en http://www.developerscrappad.com/228/java/java-ee/ejb3-jpa-dealing-with-date-time-and-timestamp/

**Comment by emiliew** [comment]
Muy buena para entender los tipos. Al final tiraré podemos tirar por esta solución: http://stackoverflow.com/questions/1908387/java-date-cut-off-time-information

**Comment by emiliew** [comment]
Listo. El modelo sería algo parecido a:

CarJPA car1 = new CarJPA("111", "brand", "model", "color");
		cal.set(Calendar.HOUR_OF_DAY, 0);
		cal.set(Calendar.MINUTE, 0);
		cal.set(Calendar.SECOND, 0);
		cal.set(Calendar.MILLISECOND, 0);
		Date trip1Date = cal.getTime();
		
		TripJPA trip1 = new TripJPA("trip1", madrid, "entrevias", trip1Date, barcelona, "La Rambla", 4, 100);
		


Modificaré el layout para que sólo muestre el día, de momento.
